<a href="https://colab.research.google.com/github/abhishikth04/FML_LAB/blob/main/APPL_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# **0 - Dimension Array**

In [ ]:
a = np.array(800)

print(a)

800


In [ ]:
b = np.array(500)
print(b)

500


In [ ]:
c = np.array(400)
print(c)



400


In [ ]:
d = np.array(900)
print(d)


900


# **1-Dimension Array**
collection of is form 1-Dimensional Array

In [ ]:
a1 = np.array([200,300,400,500,600,700,800])

print(a1)

[200 300 400 500 600 700 800]


In [ ]:
a2 = np.array([1,2,3,4,6,7,8])
print(a2)



[1 2 3 4 6 7 8]


In [ ]:
a3 = np.array([1.1,1.2,1.3,1.4,1.5])
print(a3)



[1.1 1.2 1.3 1.4 1.5]


In [ ]:
a4 = np.array([10,20,30,40,50])
print(a4)



[10 20 30 40 50]


# **2 - Dimension Array**


*   0th list
*   1st list



In [ ]:
b1 = np.array([[200,300],[400,500]])

print(b1)

[[200 300]
 [400 500]]


In [ ]:
b2 = np.array([[1,2,3],[4,5,6]])
print(b2)
print(b2[1,1])



[[1 2 3]
 [4 5 6]]
5


In [ ]:
b3 = np.array([[10,20,30],[40,50,60]])
print(b3)



[[10 20 30]
 [40 50 60]]


In [ ]:
b4 = np.array([[11,12,13,14],[15,16,17,18]])
print(b4)

print(b4[0][2])
print(b4[1][1])




[[11 12 13 14]
 [15 16 17 18]]
13
16


# **3 - Dimension Array**

In [ ]:
c1 = np.array([[[200,300],[400,500]],[[600,700],[800,900]]])

print(c1)


[[[200 300]
  [400 500]]

 [[600 700]
  [800 900]]]


In [ ]:
c2 = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(c2)


[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [ ]:
c3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c3)

print(c3[1][0][2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
9


In [ ]:
c4 = np.array([[[1.1,1.2,1.3],[1.4,1.5,1.6]],[[1.7,1.8,1.9],[2.0,2.1,2.2]]])
print(c4)

print(c4[0][0][1])

[[[1.1 1.2 1.3]
  [1.4 1.5 1.6]]

 [[1.7 1.8 1.9]
  [2.  2.1 2.2]]]
1.2


# **asarray()**

In [ ]:
d1 = [200,300,400,500]
d2 = np.asarray(d1,dtype = "float")
print(d2)

[200. 300. 400. 500.]


In [ ]:
e1 = [1,2,3,4,5,6]
e2 = np.asarray(e1,dtype = "S1")
print(e2)

[b'1' b'2' b'3' b'4' b'5' b'6']


In [ ]:
f1 = [1.1,1.2,1.3,1.4]
f2 = np.asarray(f1,dtype = "int")
print(f2)

[1 1 1 1]


In [ ]:
g1 = [5,6,7,8,9]
g2 = np.asarray(g1,dtype = "float")
print(g2)

[5. 6. 7. 8. 9.]


# **frombuffer()**



1.   Converts string into buffer
2.   place b infront of the string



In [ ]:
h1 = b"First year CSE students"
h2 = np.frombuffer(h1,dtype = "S1")
print(h2)

[b'F' b'i' b'r' b's' b't' b' ' b'y' b'e' b'a' b'r' b' ' b'C' b'S' b'E'
 b' ' b's' b't' b'u' b'd' b'e' b'n' b't' b's']


In [ ]:
# count
h3 = b"Heello World"
h4 = np.frombuffer(h3,dtype = "S1" , count = 10)
print(h4)

[b'H' b'e' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r']


In [ ]:
# offset
h5 = b"Good Morning"
h6 = np.frombuffer(h5,dtype = "S1" , count = 5 , offset = 2)
print(h6)

[b'o' b'd' b' ' b'M' b'o']


In [ ]:
h7 = b"Good Evening to all"
h8 = np.frombuffer(h7 , dtype = "S1")
print(h8)

[b'G' b'o' b'o' b'd' b' ' b'E' b'v' b'e' b'n' b'i' b'n' b'g' b' ' b't'
 b'o' b' ' b'a' b'l' b'l']


# **fromiter()**



In [ ]:
i1 = ([200,300,400,500])
i2 = np.fromiter(i1,dtype = "int" , count = 3)
print(i2)


[200 300 400]


In [ ]:
i3 = ([1,2,3,4,5])
i4 = np.fromiter(i3,dtype = "float" , count = 4)
print(i4)

[1. 2. 3. 4.]


In [ ]:
i5 = ([5,6,7,8,9,10,11,12])
i6 = np.fromiter(i5,dtype = "float" , count = 4)
print(i6)

[5. 6. 7. 8.]


In [ ]:
i7 = ([3,4,5,6,7,8])
i8 = np.fromiter(i7,dtype = "S1",count = 5)
print(i8)

[b'3' b'4' b'5' b'6' b'7']




# 1.  Row Major Order ("C")


# 2.   Coloumn Major Order ("F")







In [ ]:
a = [[200,300],[400,500]]
print(b)
b = np.asarray(a,order = "C")
for i in np.nditer(b):
  print(i)

[[200 300]
 [400 500]]
200
300
400
500


In [ ]:
a = [[200,300],[400,500]]
b = np.asarray(a,order = "F")
for i in np.nditer(b):
  print(i)

200
400
300
500


# **Initializing Arrays**

# **Zeros()**

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
np.zeros([4,5])


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a1 = np.zeros([5,4],dtype = int)
print(a1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
b = np.zeros([5,4,4])
print(b)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# **full()**

In [ ]:
c = np.full([4,4],6)
print(c)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [ ]:
d = np.full([4,4,6],8)
print(d)

[[[8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]]

 [[8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]]

 [[8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]]

 [[8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]]]


# **random.rand()**

*   Output in between 0 to 1
*   no use of subscript[]







In [ ]:
e = np.random.rand(5,6)
print(e)

[[0.30264704 0.65549418 0.8155683  0.89974238 0.01166051 0.73041487]
 [0.35043542 0.28612267 0.03980986 0.61251962 0.72228897 0.99351158]
 [0.72857158 0.48829356 0.59809249 0.89472603 0.85073082 0.26773684]
 [0.4567055  0.03308346 0.59295373 0.42656482 0.57918935 0.76660138]
 [0.05630915 0.04527299 0.32779743 0.38568412 0.11142845 0.98045879]]


In [ ]:
e1 = np.random.rand(6,5,6)
print(e1)

[[[0.76042064 0.80600799 0.39930594 0.75924661 0.94219929 0.04002343]
  [0.47628308 0.99649372 0.70382808 0.847299   0.7743173  0.96879286]
  [0.35472847 0.38818153 0.66881733 0.28347563 0.66778834 0.69337228]
  [0.01937621 0.67369893 0.18171446 0.48338386 0.47985879 0.65328023]
  [0.65258844 0.88890113 0.75603795 0.71631559 0.06315081 0.52360671]]

 [[0.21771663 0.58502687 0.65144321 0.50395623 0.58820441 0.50261046]
  [0.14873445 0.35988305 0.36663719 0.9039794  0.90553497 0.80244167]
  [0.00126888 0.38121025 0.0669321  0.25240352 0.52581395 0.73731094]
  [0.85143911 0.55319867 0.03521058 0.67529706 0.02004587 0.70314194]
  [0.23873611 0.55507732 0.30767199 0.64207622 0.39002022 0.63935253]]

 [[0.54799918 0.07722673 0.47799294 0.19534684 0.28338179 0.10069271]
  [0.82381104 0.38994977 0.86849324 0.16534233 0.28565167 0.81821163]
  [0.61138678 0.45457417 0.31494619 0.03604769 0.24415256 0.17481968]
  [0.9432975  0.65742831 0.8138423  0.16603854 0.69784612 0.77062635]
  [0.4818292  0.

# **ones()**

In [ ]:
f = np.ones([4,6],dtype = 'int')
print(f)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [ ]:
f1 = np.ones([4,4,6],dtype = int)
print(f1)

[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]]


# **eye()**



*   diagonal elements are 1 remaining are 0
* 2/2 mtrix or 4/4 matrix



In [ ]:
g = np.eye(5)
print(g)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
g1 = np.eye(8)
print(g1)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


# **NUMERICAL RANGE**


*   arange()
*   reshape()
*   linspace()
*   logspace()

values are printed between the given range

start stop step (difference)




# **arange()**

In [ ]:
h = np.arange(30,50,3)
print(h)

[30 33 36 39 42 45 48]


In [ ]:
h1 = np.arange(0,100,5,dtype = float)
print(h1)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85.
 90. 95.]


In [ ]:
h2 = np.arange(10,100,5)
print(h2)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


# **reshape()**

 equal division matrix

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
a.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
a.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
a = np.linspace(0,100,20,endpoint=False , retstep = True , dtype = int)
print(a)

(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95]), 5.0)


# **linspace()**

last element is also considered

In [ ]:
i = np.linspace(10,100,10)
print(i)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [ ]:
i1 = np.linspace(10,100,10,endpoint=False) #equal intervals 10
print(i1)

[10. 19. 28. 37. 46. 55. 64. 73. 82. 91.]


In [ ]:
i2 = np.linspace(10,100,10,endpoint = False , retstep = True , dtype = int) #equal intervals 10
print(i2)

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)


# **logspace()**

logrithemic values

In [ ]:
k = np.logspace(1,10,10,base = 2 , dtype = int )
print(k)

[   2    4    8   16   32   64  128  256  512 1024]


In [ ]:
k1 = np.logspace(1,10,10, dtype = int )
print(k1)

[         10         100        1000       10000      100000     1000000
    10000000   100000000  1000000000 10000000000]


# **ARRAY PROERTIES**

#SIZE - np.size(array)
#SHAPE - np.shape(array)
#DTYPE - a.dtype

In [ ]:
l = np.arange(10,100,10)
l

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
l1 = l.reshape(3,3)
l1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
np.size(l1)

9

In [ ]:
l1.dtype

dtype('int64')

In [ ]:
l2 = np.array([10,20,30],dtype = float)
print(l2)

[10. 20. 30.]


In [ ]:
l2.dtype

dtype('float64')

# **ARRAY OPERATIONS**


*   Accessing the elements
*   Slcing -Means extractin some portion of data

Accesing and slicing operations





1.   concatenate()
2.   copy()
3. stack()
4. view
5. vstack()
6. sort()
7. dstack()
8. reshape()
9. hstack()
10. append()
11. split()
12. insert()
13. where()
14. delete()
15. searchsorted()












# **Accessing and slicing operations**

In [ ]:
m = np.array([[23,34,45,56,67,78],[12,13,14,15,16,17]])
print(m)

[[23 34 45 56 67 78]
 [12 13 14 15 16 17]]


In [ ]:
m[0]

array([23, 34, 45, 56, 67, 78])

In [ ]:
m[1]

array([12, 13, 14, 15, 16, 17])

In [ ]:
m[1][4]

16

In [ ]:
m1 = np.arange(10,200,10)
print(m1)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190]


In [ ]:
h[5:16]

array([45, 48])

In [ ]:

m2 = np.arange(10,3000,10)
print(m2)

[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
  150  160  170  180  190  200  210  220  230  240  250  260  270  280
  290  300  310  320  330  340  350  360  370  380  390  400  410  420
  430  440  450  460  470  480  490  500  510  520  530  540  550  560
  570  580  590  600  610  620  630  640  650  660  670  680  690  700
  710  720  730  740  750  760  770  780  790  800  810  820  830  840
  850  860  870  880  890  900  910  920  930  940  950  960  970  980
  990 1000 1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110 1120
 1130 1140 1150 1160 1170 1180 1190 1200 1210 1220 1230 1240 1250 1260
 1270 1280 1290 1300 1310 1320 1330 1340 1350 1360 1370 1380 1390 1400
 1410 1420 1430 1440 1450 1460 1470 1480 1490 1500 1510 1520 1530 1540
 1550 1560 1570 1580 1590 1600 1610 1620 1630 1640 1650 1660 1670 1680
 1690 1700 1710 1720 1730 1740 1750 1760 1770 1780 1790 1800 1810 1820
 1830 1840 1850 1860 1870 1880 1890 1900 1910 1920 1930 1940 1950 1960
 1970 

In [ ]:
m2[212:312]

array([2130, 2140, 2150, 2160, 2170, 2180, 2190, 2200, 2210, 2220, 2230,
       2240, 2250, 2260, 2270, 2280, 2290, 2300, 2310, 2320, 2330, 2340,
       2350, 2360, 2370, 2380, 2390, 2400, 2410, 2420, 2430, 2440, 2450,
       2460, 2470, 2480, 2490, 2500, 2510, 2520, 2530, 2540, 2550, 2560,
       2570, 2580, 2590, 2600, 2610, 2620, 2630, 2640, 2650, 2660, 2670,
       2680, 2690, 2700, 2710, 2720, 2730, 2740, 2750, 2760, 2770, 2780,
       2790, 2800, 2810, 2820, 2830, 2840, 2850, 2860, 2870, 2880, 2890,
       2900, 2910, 2920, 2930, 2940, 2950, 2960, 2970, 2980, 2990])

# **copy()**

copyng one array eements into another array

In [ ]:
n = np.array([[234,235,236,237],[123,124,125,126]])
print(n)

[[234 235 236 237]
 [123 124 125 126]]


In [ ]:
n1 = np.copy(n)
print(n1)

[[234 235 236 237]
 [123 124 125 126]]


In [ ]:
print(n,n1)

[[234 235 236 237]
 [123 124 125 126]] [[234 235 236 237]
 [123 124 125 126]]


# **view**

similiar to copy but acts like a reference

In [ ]:
n2 = n1.view()
print(n2)

[[234 235 236 237]
 [123 124 125 126]]


In [ ]:
 print("n = ",n)
 print("n1 = ",n)
 print("n2= ",n)

n =  [[234 235 236 237]
 [123 124 125 126]]
n1 =  [[234 235 236 237]
 [123 124 125 126]]
n2=  [[234 235 236 237]
 [123 124 125 126]]


In [ ]:
n1

array([[234, 235, 236, 237],
       [123, 124, 125, 126]])

In [ ]:
n2

array([[234, 235, 236, 237],
       [123, 124, 125, 126]])

In [ ]:
n[1][2] = 777
print(n)

[[234 235 236 237]
 [123 124 777 126]]


In [ ]:
n1

array([[234, 235, 236, 237],
       [123, 124, 125, 126]])

In [ ]:
n1[0][1] = 999
n1

array([[234, 999, 236, 237],
       [123, 124, 125, 126]])

In [ ]:
n2

array([[234, 999, 236, 237],
       [123, 124, 125, 126]])

# **sort**

sorting the elements

In [ ]:
a = np.array([4535,5674,7864,9876,1234,5738,2967,2336])
print(a)

[4535 5674 7864 9876 1234 5738 2967 2336]


In [ ]:
np.sort(a)

array([1234, 2336, 2967, 4535, 5674, 5738, 7864, 9876])

In [ ]:
a = a.reshape(4,2)
print(a)

[[4535 5674]
 [7864 9876]
 [1234 5738]
 [2967 2336]]


In [ ]:
a = a.reshape(2,4)
print(a)

[[4535 5674 7864 9876]
 [1234 5738 2967 2336]]


In [ ]:
a = a.reshape(8,1)
print(a)

[[4535]
 [5674]
 [7864]
 [9876]
 [1234]
 [5738]
 [2967]
 [2336]]


In [ ]:
a = a.reshape(1,8)
print(a)

[[4535 5674 7864 9876 1234 5738 2967 2336]]


# **Based on Axis Medium , functions are implemented**



1.   Axis : 0 means column wise operations

2.   Axis : 1 row column wise operations




In [ ]:
a = np.array([[234,456,789,123,999,899],[543,654,765,876,987,876]])
print(a)

[[234 456 789 123 999 899]
 [543 654 765 876 987 876]]


In [ ]:
np.sort(a,axis = 0) #coloumn wise elements are sorted

array([[234, 456, 765, 123, 987, 876],
       [543, 654, 789, 876, 999, 899]])

In [ ]:
np.sort(a,axis = 1) #row wise elements are sorted

array([[123, 234, 456, 789, 899, 999],
       [543, 654, 765, 876, 876, 987]])

#**In single dimension it will sort automatically**
#**In multi Dimension it will be sorted based on Axis**
#**If we dont mention anything , by default it takes row wise Axis-Operations**


In [ ]:
d = np.dtype([('name','S1'),('perc',float)])

In [ ]:
marks = np.array([("h",99.8),("I",98.3),("a",99.9)],dtype = d)


In [ ]:
marks

array([(b'h', 99.8), (b'I', 98.3), (b'a', 99.9)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
np.sort(marks , order = "name")

array([(b'I', 98.3), (b'a', 99.9), (b'h', 99.8)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
np.sort(marks , order = "perc")

array([(b'I', 98.3), (b'h', 99.8), (b'a', 99.9)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

# **reshape**

In [ ]:
a = np.array([234,345,456,567,678,789,890,999,111,222,333,345])
print(a)

[234 345 456 567 678 789 890 999 111 222 333 345]


In [ ]:
a.reshape(2,6)

array([[234, 345, 456, 567, 678, 789],
       [890, 999, 111, 222, 333, 345]])

In [ ]:
a = np.arange(20,180,10)
print(a)

[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170]


In [ ]:
a.reshape(2,8)

array([[ 20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170]])

In [ ]:
a.reshape(8,2)

array([[ 20,  30],
       [ 40,  50],
       [ 60,  70],
       [ 80,  90],
       [100, 110],
       [120, 130],
       [140, 150],
       [160, 170]])

In [ ]:
a.reshape(4,4)

array([[ 20,  30,  40,  50],
       [ 60,  70,  80,  90],
       [100, 110, 120, 130],
       [140, 150, 160, 170]])

In [ ]:
a.reshape(2,4,2)

array([[[ 20,  30],
        [ 40,  50],
        [ 60,  70],
        [ 80,  90]],

       [[100, 110],
        [120, 130],
        [140, 150],
        [160, 170]]])

In [ ]:
a.reshape(2,2,2,2)

array([[[[ 20,  30],
         [ 40,  50]],

        [[ 60,  70],
         [ 80,  90]]],


       [[[100, 110],
         [120, 130]],

        [[140, 150],
         [160, 170]]]])

# **append**

append is applied between arrays



In [ ]:
a = np.array([234,345,456,567,678,578,789,890,901,122,132,111])
print(a)

[234 345 456 567 678 578 789 890 901 122 132 111]


In [ ]:
b = np.array([234,345,456,467,178,878,719,800,911,822,112,111])
print(b)


[234 345 456 467 178 878 719 800 911 822 112 111]


In [ ]:
np.append(a,b)

array([234, 345, 456, 567, 678, 578, 789, 890, 901, 122, 132, 111, 234,
       345, 456, 467, 178, 878, 719, 800, 911, 822, 112, 111])

In [ ]:
a = np.array([[234,345,456,567,678,578],[789,890,901,122,132,111]])
print(a)

[[234 345 456 567 678 578]
 [789 890 901 122 132 111]]


In [ ]:
b = np.array([[134,245,356,467,568,678],[789,890,901,122,232,311]])
print(b)

[[134 245 356 467 568 678]
 [789 890 901 122 232 311]]


In [ ]:
np.append(a,b) #forms a single dimension array if you are giving mumti dimension array

array([234, 345, 456, 567, 678, 578, 789, 890, 901, 122, 132, 111, 134,
       245, 356, 467, 568, 678, 789, 890, 901, 122, 232, 311])

In [ ]:
np.append(a,b).reshape(6,4)

array([[234, 345, 456, 567],
       [678, 578, 789, 890],
       [901, 122, 132, 111],
       [134, 245, 356, 467],
       [568, 678, 789, 890],
       [901, 122, 232, 311]])

In [ ]:
np.append(a,b).reshape(2,12)

array([[234, 345, 456, 567, 678, 578, 789, 890, 901, 122, 132, 111],
       [134, 245, 356, 467, 568, 678, 789, 890, 901, 122, 232, 311]])

In [ ]:
np.append(a,b).reshape(12,2)

array([[234, 345],
       [456, 567],
       [678, 578],
       [789, 890],
       [901, 122],
       [132, 111],
       [134, 245],
       [356, 467],
       [568, 678],
       [789, 890],
       [901, 122],
       [232, 311]])

In [ ]:
np.append(a,b).reshape(24,1)

array([[234],
       [345],
       [456],
       [567],
       [678],
       [578],
       [789],
       [890],
       [901],
       [122],
       [132],
       [111],
       [134],
       [245],
       [356],
       [467],
       [568],
       [678],
       [789],
       [890],
       [901],
       [122],
       [232],
       [311]])

In [ ]:
np.append(a,b).reshape(3,4,2)

array([[[234, 345],
        [456, 567],
        [678, 578],
        [789, 890]],

       [[901, 122],
        [132, 111],
        [134, 245],
        [356, 467]],

       [[568, 678],
        [789, 890],
        [901, 122],
        [232, 311]]])

In [ ]:
np.append(a,b).reshape(4,2,3)

array([[[234, 345, 456],
        [567, 678, 578]],

       [[789, 890, 901],
        [122, 132, 111]],

       [[134, 245, 356],
        [467, 568, 678]],

       [[789, 890, 901],
        [122, 232, 311]]])

In [ ]:
np.append(a,b).reshape(4,3,2)

array([[[234, 345],
        [456, 567],
        [678, 578]],

       [[789, 890],
        [901, 122],
        [132, 111]],

       [[134, 245],
        [356, 467],
        [568, 678]],

       [[789, 890],
        [901, 122],
        [232, 311]]])

# **insert()**


1.   insert is also similar to append
2.   insert is taken single dimension continuos memory location index array



In [ ]:
a = np.array([[234,345,456,567,678,789],[543,500,276,564,785,111]])
print(a)

[[234 345 456 567 678 789]
 [543 500 276 564 785 111]]


In [ ]:
np.insert(a,7,999) #inserting single element

array([234, 345, 456, 567, 678, 789, 543, 999, 500, 276, 564, 785, 111])

In [ ]:
np.insert(a,7,[999,636,777,234]) #inserting multiple elements
#result generated in single dimension only
#subscript[] is used for inserting multiple elements

array([234, 345, 456, 567, 678, 789, 543, 999, 636, 777, 234, 500, 276,
       564, 785, 111])

In [ ]:
np.insert(a,7,[999,654,777,124]).reshape(4,4)

array([[234, 345, 456, 567],
       [678, 789, 543, 999],
       [654, 777, 124, 500],
       [276, 564, 785, 111]])

In [ ]:
np.insert(a,7,[999,654,777,124]).reshape(2,4,2)

array([[[234, 345],
        [456, 567],
        [678, 789],
        [543, 999]],

       [[654, 777],
        [124, 500],
        [276, 564],
        [785, 111]]])

In [ ]:
np.insert(a,7,[999,654,777,124]).reshape(2,2,2,2)

array([[[[234, 345],
         [456, 567]],

        [[678, 789],
         [543, 999]]],


       [[[654, 777],
         [124, 500]],

        [[276, 564],
         [785, 111]]]])

# **Delete**()

In [ ]:
a = np.array([234,345,456,567,678,890,132,434,857,865,111,689])
print(a)

[234 345 456 567 678 890 132 434 857 865 111 689]


In [ ]:
np.delete(a,9)

array([234, 345, 456, 567, 678, 890, 132, 434, 857, 111, 689])

In [ ]:
a = np.array([[234,345,456,567,678,890],[132,434,857,865,111,689]])
print(a)


[[234 345 456 567 678 890]
 [132 434 857 865 111 689]]


In [ ]:
np.delete(a,6)

array([234, 345, 456, 567, 678, 890, 434, 857, 865, 111, 689])

# **concatenate**()

two different arrays are concatenated

In [ ]:
a = np.array([234,345,456,567,678,890,132,434,857,865,111,689])
a

array([234, 345, 456, 567, 678, 890, 132, 434, 857, 865, 111, 689])

In [ ]:
b = np.array([235,145,444,927,446,990,113,111,850,405,420,699])
b

array([235, 145, 444, 927, 446, 990, 113, 111, 850, 405, 420, 699])

In [ ]:
np.concatenate((a,b)) # all elements will be in one dimension only

array([234, 345, 456, 567, 678, 890, 132, 434, 857, 865, 111, 689, 235,
       145, 444, 927, 446, 990, 113, 111, 850, 405, 420, 699])

In [ ]:
np.concatenate((a,b),axis=0) # row wise concatenation

array([234, 345, 456, 567, 678, 890, 132, 434, 857, 865, 111, 689, 235,
       145, 444, 927, 446, 990, 113, 111, 850, 405, 420, 699])

# **stack**()

# **vstack**()

# **hstack**()

# **dstack**()

these are all used for joining arrays

In [ ]:
a = np.array([234,345,456,567,678,890,132,434,857,865,111,689])
print(a)

[234 345 456 567 678 890 132 434 857 865 111 689]


In [ ]:
b = np.array([235,145,444,927,446,990,113,111,850,405,420,699])
print(b)

[235 145 444 927 446 990 113 111 850 405 420 699]


In [ ]:
np.stack((a,b))
# stack seperates two array elements but concatebnation not seperated the array elements

array([[234, 345, 456, 567, 678, 890, 132, 434, 857, 865, 111, 689],
       [235, 145, 444, 927, 446, 990, 113, 111, 850, 405, 420, 699]])

In [ ]:
res = np.stack((a,b))
res


array([[234, 345, 456, 567, 678, 890, 132, 434, 857, 865, 111, 689],
       [235, 145, 444, 927, 446, 990, 113, 111, 850, 405, 420, 699]])

In [ ]:
res[0]

array([234, 345, 456, 567, 678, 890, 132, 434, 857, 865, 111, 689])

In [ ]:
res[1]

array([235, 145, 444, 927, 446, 990, 113, 111, 850, 405, 420, 699])

In [ ]:
res1 = np.concatenate((a,b))

In [ ]:
res1

array([234, 345, 456, 567, 678, 890, 132, 434, 857, 865, 111, 689, 235,
       145, 444, 927, 446, 990, 113, 111, 850, 405, 420, 699])

In [ ]:
res1[9]

865

In [ ]:
np.stack((a,b),axis = 1) # first row of a and first row of b form an array


array([[234, 235],
       [345, 145],
       [456, 444],
       [567, 927],
       [678, 446],
       [890, 990],
       [132, 113],
       [434, 111],
       [857, 850],
       [865, 405],
       [111, 420],
       [689, 699]])

In [ ]:
np.stack((a,b),axis = 0)


array([[234, 345, 456, 567, 678, 890, 132, 434, 857, 865, 111, 689],
       [235, 145, 444, 927, 446, 990, 113, 111, 850, 405, 420, 699]])

# **vstack**()

Vertical stack

In [ ]:
a = np.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

In [ ]:
b = np.array([[50,60],[70,80]])
b

array([[50, 60],
       [70, 80]])

In [ ]:
np.vstack((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

# **hstack**()

horizontal stack

In [ ]:
np.hstack((a,b)) #concatenation w.r.t. axis = 1

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [ ]:
np.concatenate((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [ ]:
np.concatenate((a,b),axis = 1)

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

# **Depth wise**

# **dstack**()

In [ ]:
a = np.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

In [ ]:
b = np.array([[50,60],[70,80]])
b

array([[50, 60],
       [70, 80]])

In [ ]:
np.dstack((a,b))

array([[[10, 50],
        [20, 60]],

       [[30, 70],
        [40, 80]]])

# **split()**

In [ ]:
x = np.arange(5,60,2)
print(x)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59]


In [ ]:
np.split(x,7) #equal divisions

[array([ 5,  7,  9, 11]),
 array([13, 15, 17, 19]),
 array([21, 23, 25, 27]),
 array([29, 31, 33, 35]),
 array([37, 39, 41, 43]),
 array([45, 47, 49, 51]),
 array([53, 55, 57, 59])]

In [ ]:
np.split(x,2)

[array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]),
 array([33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59])]

In [ ]:
np.split(x,14)

[array([5, 7]),
 array([ 9, 11]),
 array([13, 15]),
 array([17, 19]),
 array([21, 23]),
 array([25, 27]),
 array([29, 31]),
 array([33, 35]),
 array([37, 39]),
 array([41, 43]),
 array([45, 47]),
 array([49, 51]),
 array([53, 55]),
 array([57, 59])]

In [ ]:
np.split(x,7)

[array([ 5,  7,  9, 11]),
 array([13, 15, 17, 19]),
 array([21, 23, 25, 27]),
 array([29, 31, 33, 35]),
 array([37, 39, 41, 43]),
 array([45, 47, 49, 51]),
 array([53, 55, 57, 59])]

In [ ]:
z = np.split(x,7)
print(z)

[array([ 5,  7,  9, 11]), array([13, 15, 17, 19]), array([21, 23, 25, 27]), array([29, 31, 33, 35]), array([37, 39, 41, 43]), array([45, 47, 49, 51]), array([53, 55, 57, 59])]


In [ ]:
s1,s2,s3,s4,s5,s6,s7 = np.split(x,7)  #equal divisions

In [ ]:
s1

array([ 5,  7,  9, 11])

In [ ]:
s2

array([13, 15, 17, 19])

In [ ]:
s3

array([21, 23, 25, 27])

In [ ]:
s4

array([29, 31, 33, 35])

In [ ]:
s5

array([37, 39, 41, 43])

In [ ]:
s6

array([45, 47, 49, 51])

In [ ]:
s7

array([53, 55, 57, 59])

# **where**()

it checks wether theelements are present in the array or not

In [ ]:
a

array([[10, 20],
       [30, 40]])

In [ ]:
a = np.arange(5,65,5).reshape(4,3)
a

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [ ]:
np.where(a==55)

(array([3]), array([1]))

In [ ]:
a = np.arange(5,65,5).reshape(6,2)
a

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50],
       [55, 60]])

In [ ]:
np.where(a==40)

(array([3]), array([1]))

In [ ]:
b = np.arange(10,100,6)
b

array([10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76, 82, 88, 94])

In [ ]:
np.where(b==52)

(array([7]),)

In [ ]:
a

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50],
       [55, 60]])

In [ ]:
np.where(a%20==0)

(array([1, 3, 5]), array([1, 1, 1]))

# **searchsorted**()

In [ ]:
a = np.array([234,345,456,567,678,890,132,434])
a


array([234, 345, 456, 567, 678, 890, 132, 434])

In [ ]:
np.searchsorted(a,567)

3

#**Arithmetic Operations**


*   add()
*   subtract()
*   multily()
*   divide()
*   exp()
*   sqrt()
*   comparision()



# **Addition**

add()

In [ ]:
a = np.array([[22,25,45],[65,78,56]])
print(a)

[[22 25 45]
 [65 78 56]]


In [ ]:
b = np.array([[72,66,95],[42,78,69]])
print(b)

[[72 66 95]
 [42 78 69]]


In [ ]:
np.add(a,b)

array([[ 94,  91, 140],
       [107, 156, 125]])

# **subtract**

subtract()

In [ ]:
np.subtract(a,b)

array([[-50, -41, -50],
       [ 23,   0, -13]])

# **Multiply**

multiply()


In [ ]:
np.multiply(a,b)

array([[1584, 1650, 4275],
       [2730, 6084, 3864]])

# **Divide**

divide()

In [ ]:
np.divide(a,b)

array([[0.30555556, 0.37878788, 0.47368421],
       [1.54761905, 1.        , 0.8115942 ]])

# **Exponential**

exp()

In [ ]:
np.exp(a)

array([[3.58491285e+09, 7.20048993e+10, 3.49342711e+19],
       [1.69488924e+28, 7.49841700e+33, 2.09165950e+24]])

In [ ]:
np.exp(b)

array([[1.85867175e+31, 4.60718663e+28, 1.81123908e+41],
       [1.73927494e+18, 7.49841700e+33, 9.25378173e+29]])

#**SquareRoot**

sqrt()

In [ ]:
np.sqrt(a)

array([[4.69041576, 5.        , 6.70820393],
       [8.06225775, 8.83176087, 7.48331477]])

In [ ]:
np.sqrt(b)

array([[8.48528137, 8.1240384 , 9.74679434],
       [6.4807407 , 8.83176087, 8.30662386]])

# **Comparision**

In [ ]:
# "==" is applied in comparision
a

array([[22, 25, 45],
       [65, 78, 56]])

In [ ]:
b

array([[72, 66, 95],
       [42, 78, 69]])

In [ ]:
b[1][0] = 65
b[1][1] = 74
b[1][2] = 87

In [ ]:
b

array([[72, 66, 95],
       [65, 74, 87]])

In [ ]:
np.array_equal(a,b)

False

In [ ]:
a == b

array([[False, False, False],
       [ True, False, False]])

# **ARRAY FUNCTIONS**


*   sum()
*   min()
*   max()
*   mean()
*   median()
*   var()
*   std()




# **min**()

In [ ]:
a = np.array([[100,200],[300,400],[500,600]])
a

array([[100, 200],
       [300, 400],
       [500, 600]])

In [ ]:
np.min(a)

100

In [ ]:
np.min(a,axis = 1)

array([100, 300, 500])

In [ ]:
np.min(a,axis = 0)

array([100, 200])

# **max**()

In [ ]:
np.max(a)

600

In [ ]:
np.max(a,axis = 1)

array([200, 400, 600])

In [ ]:
np.min(a,axis = 0)

array([100, 200])

# **sum**()

In [ ]:
np.sum(a)

2100

In [ ]:
np.sum(a,axis = 1)

array([ 300,  700, 1100])

In [ ]:
np.sum(a,axis = 0)

array([ 900, 1200])

# **mean**()

average

In [ ]:
np.mean(a)

350.0

In [ ]:
np.mean(a,axis = 1)

array([150., 350., 550.])

In [ ]:
np.mean(a,axis = 0)

array([300., 400.])

# **meadian**()

In [ ]:
np.median(a)

350.0

In [ ]:
np.median(a,axis = 1)

array([150., 350., 550.])

In [ ]:
np.median(a,axis = 0)

array([300., 400.])

# **var**()

variance

In [ ]:
np.var(a)

29166.666666666668

In [ ]:
np.var(a,axis = 1)

array([2500., 2500., 2500.])

In [ ]:
np.var(a,axis = 0)

array([26666.66666667, 26666.66666667])

# **std**()

In [ ]:
np.std(a)

170.78251276599332

In [ ]:
np.std(a,axis = 1)

array([50., 50., 50.])

In [ ]:
np.std(a,axis = 0)

array([163.29931619, 163.29931619])